# Generated by Django 2.2.1 on 2019-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('dt_create',),
            },
        ),
    ]
