# Generated by Django 2.2.1 on 2019-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Em andamento'), (3, 'Finalizada')]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
